
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wallets_development

test:
  <<: *default
  database: walletsrake _test

production:
  <<: *default
  database: lists_production
  username: lists
  password: <%= ENV['LISTS_DATABASE_PASSWORD'] %>
